export enum UserRole {
  PLATFORM_ADMIN = "PLATFORM_ADMIN",
  TENANT_ADMIN = "TENANT_ADMIN",
  OPERATIONS_MANAGER = "OPERATIONS_MANAGER",
  WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER",
  DRIVER = "DRIVER",
}
