export enum UserRole {
  TENANT_ADMIN = "TENANT_ADMIN",
  OPERATIONS_MANAGER = "OPERATIONS_MANAGER",
  WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER",
  DRIVER = "DRIVER",
  CUSTOMER_USER = "CUSTOMER_USER",
  PLATFORM_ADMIN = "PLATFORM_ADMIN",
}
